// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Milestone row returned inside a project detail response.
 */
export type MilestoneSummary = { id: number, name: string, description: string | null, status: string, target_date: string | null, due_date: string | null, sort_order: number, task_count: number, };
