// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * List view: project + aggregate counts from subqueries.
 */
export type ProjectListItem = { id: number, name: string, description: string | null, status: string, target_date: string | null, created_at: string | null, updated_at: string | null, member_count: number, open_task_count: number, };
