// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MilestoneSummary } from "./MilestoneSummary";

/**
 * Detail view: project + its milestones.
 */
export type ProjectDetail = { milestones: Array<MilestoneSummary>, id: number, name: string, description: string | null, status: string, target_date: string | null, created_at: string | null, updated_at: string | null, };
