// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: number, name: string, description: string | null, status: string, target_date: string | null, created_at: string | null, updated_at: string | null, };
