// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: number, project_id: number, milestone_id: number | null, title: string, description: string | null, status: string, priority: string, due_date: string | null, sort_order: number, created_by: number, created_at: string | null, updated_at: string | null, };
